import aws from '/public/svg/skills/aws.svg';
import bootstrap from '/public/svg/skills/bootstrap.svg';
import c from '/public/svg/skills/c.svg';
import css from '/public/svg/skills/css.svg';
import firebase from '/public/svg/skills/firebase.svg';
import git from '/public/svg/skills/git.svg';
import html from '/public/svg/skills/html.svg';
import java from '/public/svg/skills/java.svg';
import javascript from '/public/svg/skills/javascript.svg';
import kotlin from '/public/svg/skills/kotlin.svg';
import mongoDB from '/public/svg/skills/mongoDB.svg';
import mysql from '/public/svg/skills/mysql.svg';
import nextJS from '/public/svg/skills/nextJS.svg';
import nuxtJS from '/public/svg/skills/nuxtJS.svg';
import php from '/public/svg/skills/php.svg';
import postgresql from '/public/svg/skills/postgresql.svg';
import python from '/public/svg/skills/python.svg';
import pytorch from '/public/svg/skills/pytorch.svg';
import react from '/public/svg/skills/react.svg';
import ruby from '/public/svg/skills/ruby.svg';
import svelte from '/public/svg/skills/svelte.svg';
import tailwind from '/public/svg/skills/tailwind.svg';
import typescript from '/public/svg/skills/typescript.svg';
import vitejs from '/public/svg/skills/vitejs.svg';
import vue from '/public/svg/skills/vue.svg';
import vuetifyjs from '/public/svg/skills/vuetifyjs.svg';
import nessus from '/public/svg/skills/nessus.svg'; 
import Linux from '/public/svg/skills/linux.svg';
import Malware from '/public/svg/skills/malware.svg';
import Burpsuite from '/public/svg/skills/burpsuite.svg';
import WireShark from '/public/svg/skills/wireShark.svg';
import Nikto from '/public/svg/skills/nikto.svg';
import openvas from '/public/svg/skills/OpenVas.svg';

export const skillsImage = (skill) => {
  const skillID = skill.toLowerCase();
  switch (skillID) {
    case 'html': return html;
    case 'css': return css;
    case 'javascript': return javascript;
    case 'next js': return nextJS;
    case 'nuxt js': return nuxtJS;
    case 'react': return react;
    case 'svelte': return svelte;
    case 'typescript': return typescript;
    case 'vue': return vue;
    case 'bootstrap': return bootstrap;
    case 'mongodb': return mongoDB;
    case 'mysql': return mysql;
    case 'postgresql': return postgresql;
    case 'tailwind': return tailwind;
    case 'vitejs': return vitejs;
    case 'vuetifyjs': return vuetifyjs;
    case 'c': return c;
    case 'java': return java;
    case 'linux': return Linux;
    case 'malware': return Malware;
    case 'burpsuite': return Burpsuite;
    case 'wireshark': return WireShark;
    case 'nikto': return Nikto;
    case 'kotlin': return kotlin;
    case 'php': return php;
    case 'python': return python;
    case 'ruby': return ruby;
    case 'aws': return aws;
    case 'firebase': return firebase;
    case 'git': return git;
    case 'pytorch': return pytorch;
    case 'nessus': return nessus;
    case 'openvas': return openvas; 
    default:
      return null;
  }
};
